services:
  postgres:
    image: postgres:16
    container_name: persistence_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./schema:/schema:ro
      - ./init/load_schema.sql:/docker-entrypoint-initdb.d/01_load_schema.sql:ro
    networks:
      - data_pipeline

volumes:
  pg_data:

networks:
  data_pipeline:
    name: data_pipeline
